### ISSUE TITLE
banners not showing

### ISSUE THREAD

**Issue by jenniestrongbow** [clockbyte/admobadapter#114]
Hello, our AdmobBannerAdapterWrapper simply never displays ads. It only displays a blank space. And the ads have enough space. 

We're using version 1.4.6.

adapterWrapper = AdmobBannerAdapterWrapper.builder(activity)
.setLimitOfAds(10)
.setFirstAdIndex(2)
.setNoOfDataBetweenAds(10)
.setAdapter(adapter)
.setAdViewWrappingStrategy(new BannerAdViewWrappingStrategy())
.build();
listview.setAdapter(adapterWrapper);

Please help. 

Thanks

**Comment by kot331107** [comment]
Hi,
how long time ago have you created a new banner in your Admob console?

**Comment by jenniestrongbow** [comment]
I tried with two AdMob banners. One I created months ago. And one I created a couple of days earlier. Thanks

**Comment by kot331107** [comment]
@jenniestrongbow could you please share some test project to reproduce it? Could you reproduce it with our **sampleapp** project?

**Comment by jenniestrongbow** [comment]
I am sorry I wasted your time. It is working fine. I was just not giving my ads enough space for them to show. Thanks for your time.

**Comment by kot331107** [comment]
@jenniestrongbow welcome! actually I have wasted no time at all, you solved the issue yourself :)

**Comment by Mayur-007** [comment]
@jenniestrongbow 
How you solved it? facing the same issue.

**Comment by Mayur-007** [comment]
Super Upset by your library.
Wasted almost 5 hours and found the problem that I had given padding in RecyclerView.
Please write this thing on the home page of the library in big font.
"Do not set padding or margin to List", so other people can be saved.

**Comment by kot331107** [comment]
@Mayur-007 Please go to RTFM and see https://github.com/clockbyte/admobadapter/wiki/Cookbook#howto-handle-the-error-wads-not-enough-space-to-show-ad-wants-320-100-has-300-100 :)

**Comment by Mayur-007** [comment]
I've read manual
https://github.com/clockbyte/admobadapter/wiki/Cookbook#the-recipe-3-for-a-recyclerview-scrolling-with-banners
I wasn't getting any error (Technically), so did not see any logs and couldn't realize, it was just blank space.
The least you can do is prevent it.
Rather than making people find an error and then providing a solution, you can do something that they don't find the error in the first place; like making a note as in requirements and write this thing in it.

**Comment by kot331107** [comment]
@Mayur-007 Look friend, have you tried to look into the LogCat with error level = DEBUG and a filter like "ads"? It should warn you about the ad's size.

**Comment by Mayur-007** [comment]
I got it resolved, but now I'm facing the wrong position in RecyclerView.
I looked at [this](https://github.com/clockbyte/admobadapter/wiki/Cookbook#in-case-you-stucked-with-getting-the-correct-itemindex-of-a-source-collection-in-a-listviewrecyclerview-click-handler) but I don't think RecyclerView has a setOnItemClickListener method.
& I want the correct index inside Adapter rather than in Activity.
