### ISSUE TITLE
what to put in the release instead of test device id?

### ISSUE THREAD

**Issue by devasish11** [clockbyte/admobadapter#130]
**Admobadapter version :*1.4.6*

*Android compileSdkVersion:*28*

I have successfully implemented the wrapper in my code, and it is properly showing native test ads with my device id. Now I want to make a release, but I am not sure what to put in the string array testdevice ids, and how to put it in.

Can anyone please write an example with a demo app id? will putting my app id or native advanced ad unit id directly in the place of the string array reference would do? I am precisely talking about below 2 lines:
    `String[] testDevicesIds = new String[]{"mymobiledeviceidfortestad",AdRequest.DEVICE_ID_EMULATOR};
`
`                        adapterWrapper = new AdmobAdapterWrapper(MainActivity.this,testDevicesIds);
`

**Comment by kot331107** [comment]
Hey @devasish11 I'd recommend you to use one of that ctors https://github.com/clockbyte/admobadapter/blob/master/admobadapter/src/main/java/com/clockbyte/admobadapter/AdmobAdapterWrapper.java#L203 which have a `release ad Id` in its args. You can get one in your AdMob console - just register your app there and create any banner there. Then you will be able to get a release Id from it, just copy and paste it to that `AdmobAdapterWrapper` ctor and you will starting to get your real ads. And fyi it could take some time to get your ad ID activated, as I remember it could take about a few hours from a creation of banner (see https://groups.google.com/forum/#!topic/google-admob-ads-sdk/yCiMLY3eqNE). Otherwise it should show you an appropriate error in your LogCat.

**Comment by devasish11** [comment]
I already have the id from admob for Native advanced type of ads, so I am gonna put it in the AdmobAdapterWrapper replacing the testDevicesIds and see how it goes, thank you for the reply!
