### ISSUE TITLE
Change Layout of Ad

### ISSUE THREAD

**Issue by hirakchhatbar** [clockbyte/admobadapter#31]
How do I change layout of Ad. The current ad view is making the list look ugly.
Is it possible by adding project in gradle or I have to manually copy paste all required classes to my project to customize layout?

**Comment by kot331107** [comment]
@hirakchhatbar Do you really expect the beatiful layout for free? :) :100:  The current layout was implemented only for demonstration... To be serious I got that you talking about Advanced ads ... I should warn you that it is unreleased by Admob yet than you could take a look at the Express ads instead of Advanced ones (see  the recipe 3 https://github.com/clockbyte/admobadapter/wiki/Cookbook#the-recipe-3-for-the-recyclerview-scrolling-with-express-ads). The layout for Express ads could be customized in your Admob console while creation of a native banner.
However, **YES** you could set you own layouts for the both InstallApps and Content types of Advanced ads with the following codesnippet (also see Recipe 1 or 2)
```java
//inject your custom layout and strategy of binding for installapp/content  ads
//here you should pass the extended NativeAdLayoutContext
//by default it has a value InstallAppAdLayoutContext.getDefault()
InstallAppAdLayoutContext installContext  = new InstallAppAdLayoutContext(R.layout.yourInstallAdLayout);
adapterWrapper.setInstallAdsLayoutContext(...);
//by default it has a value ContentAdLayoutContext.getDefault()
ContentAdLayoutContext installContext  = new ContentAdLayoutContext (R.layout.yourContentAdLayout);
adapterWrapper.setContentAdsLayoutContext(...);
```
Also instead our  InstallAppAdLayoutContext/ContentAdLayoutContext  you could  use your own binding strategy. Just extend these classes overriding the method bind(). See the code to get it better :)
