### ISSUE TITLE
Hide blank space before loading

### ISSUE THREAD

**Issue by binu8051** [clockbyte/admobadapter#47]
Hi
Using it in one of my app, how to hide the blank space of the add before the ad gets loading.
Binu

**Comment by kot331107** [comment]
@binu8051 Hi!

I suppose it's against Admob policies to show ad block suddenly by expanding it from between the items because user can click on it randomly. So we need to show the place where the ad will be presented. In the first versions of lib (in v1.2 I guess) we kept ad block hidden till it would be loaded. However you can decorate this empty place to be more user-friendly, please see
https://github.com/clockbyte/admobadapter/wiki/Cookbook#in-case-you-want-to-wrap-your-ad-blocks-into-a-viewgroup-cardview-framelayout-etc

KR
