### ISSUE TITLE
When has network connection again, express native ads are not loaded

### ISSUE THREAD

**Issue by vanhung1710** [clockbyte/admobadapter#63]
When device does not network connection, express native ads are not loaded. But when device has network connection again, express native ads are not still loaded because all native ad views in list view are set gone. I think so.

**Comment by MohaidYouness** [comment]
Hi vanhung1710
are you using popBackStack?

**Comment by kot331107** [comment]
@vanhung1710 Admobadapter doesn't handle an internet connection state. So I guess you could handle a changing of a network state in your code yourself and if the network is OK then signal to your dataset adapter by method notifyDatasetChanged() or something like this. Then Admobadapter should handle the ads update itself.

**Comment by vanhung1710** [comment]
When network connect is available, I must recreate AdmobAdapter to load ads. If I only use method notifyDatasetChanged(), ads does not show.

**Comment by kot331107** [comment]
@vanhung1710 Uhm, okay, I'll check that...

**Comment by kot331107** [comment]
@vanhung1710 Actually you could try to call the `AdmobExpressAdapterWrapper::reinitialize()` instead of recreation of AdmobAdapter on network was enabled. The same method exists but a bit buggy for now in the AdmobExpressRecyclerAdapterWrapper. I'm optimizing it right now.
And sorry for such a late answer.
